<?php /* Style for XJS Popup Generated by Bugfish Framework XJS Functions */?>
/******************************************************* XJS Popups  *********/
	#xjs_popup_inner { padding: 25px; }
	#xjs_popup {
		text-align: left;
		position: fixed;
		width: 100vw;
		height: 100vh;
		top: 0px;
		left: 0px;
		margin: 0 0 0 0;
		padding: 0 0 0 0;
		background: rgba(0, 0, 0, 0.8);
		z-index: 2000;
		color: black;}
	#xjs_popup_inner {
		position: fixed;
		left: 50%;
		top: 50%;
		transform: translate(-50%, -50%);
		width: 90%;
		max-width: 600px;
		margin: 0 0 0 0;
		padding: 0 0 0 0;
		background: white;
		border-radius: 8px;
		margin-left: 2%;
		margin-right: 2%;}
	#xjs_popup_inner {
		padding: 25px;}
	#xjs_popup_close {
		float: right;
		background: red;
		text-align: center;
		color: white;
		border-radius: 6px;
		cursor: pointer;
		padding: 5px;
		font-size: 12px;}
	#xjs_popup_close:hover {
		background: #242424;
		text-align: center;
		color: white;
		border-radius: 6px;}