<?php /* Style for Generated by Bugfish Framework Eventbox Class Functions */?>
/******************************************************* x_class_eventbox  *********/
.x_class_eventbox {
	position: fixed;
	top: 60px;
	right: 15px;
	z-index: 1000 !important;
}

.x_class_eventbox_inner {
	max-width: 500px;
}
.x_class_eventbox_msg {
	max-width: 500px;
	border-radius: 5px;
	padding: 15px;
	margin-top: 20px;
}
.x_class_eventbox_msg_ok {
	background: lime;
}
.x_class_eventbox_msg_error {
	background: red;
	color: white;
}
.x_class_eventbox_msg_warning {
	background: yellow;
}
.x_class_eventbox_msg_info {
	background: blue;
	color: white;
}
.x_class_eventbox_msg_close {
	background: red;
	border-radius: 5px;
	padding: 5px;
	color: white;
	cursor: pointer;
	width: 80px;
	font-weight: bold;
	font-size: 12px;
	position: absolute;
	float: right;
	right: 15px;
	border: 1px solid black;
}

.x_class_eventbox_msg_text { }